### ISSUE TITLE
Make this the canonical documentation site

### ISSUE THREAD

**Issue by tijmenb** [alphagov/tdt-documentation#58]
We currently have the [tech-docs-manual](https://github.com/alphagov/tech-docs-manual) (live on [github pages](https://alphagov.github.io/tech-docs-manual/#tech-docs-template)) and this site (tdt-documentation.london.cloudapps.digital).

It would be good to make this repo the single source of documentation, and archive the other one.

## Todo

- [x] Decide on the branding (https://github.com/alphagov/tdt-documentation/pull/55)
- [x] Fact check the docs by a developer
  - [x] https://tdt-documentation.london.cloudapps.digital/install_macs.html - https://github.com/alphagov/tdt-documentation/pull/56
  - [x] https://tdt-documentation.london.cloudapps.digital/create_new_project.html - https://github.com/alphagov/tdt-documentation/pull/57
- [x] Make all GitHub repos link to the new docs (the link next to the description)
- [x] Add links in the READMEs to the new docs
- [x] Archive https://github.com/alphagov/tech-docs-manual
- [x] Redirect https://alphagov.github.io/tech-docs-manual

**Comment by tijmenb** [comment]
The old tech docs site has been retired and redirected, so this issue is now closed!

https://github.com/alphagov/tech-docs-manual
